templates_dir: templates
csv_dir: csv
base_url: https://pyjok.es

build:
  pages_dir: pages
  static_dir: static
  output_dir: www

logs:
  logs_dir: apache2
  pattern: "pyjok.es-access*"

analytics:
  output_dir: analytics
  manifest_path: www/manifest.json